name: ✨ Feature request
description: Suggest an improvement or new feature
title: "[Feature]: "
labels: ["enhancement"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for the suggestion! Please describe the feature and why it would be useful.
        Note: Feature requests are not guaranteed, but I read all of them.

  - type: checkboxes
    id: duplicates
    attributes:
      label: Checks
      options:
        - label: I searched existing issues and didn't find a duplicate.
          required: true

  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve?
      description: Describe the use-case / pain point.
      placeholder: "I find it difficult to..."
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe what you would like to happen.
      placeholder: "Add an option to..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any other approaches you tried or considered.
      placeholder: "Alternatively, we could..."
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Screenshots, references, links, mockups, etc.
    validations:
      required: false
